dist: trusty
language: python
install:
- pip install -r requirements.txt
addons:
  firefox: latest
  sonarcloud:
    organization: iiiiio
    token:
      secure: pawso2YR4yr6ZibQoP5XViRj3wJ3G3+1+yybCiunlEwMJvbzIxSR5gtm1rHwj0ETfb45YbAwZChxYzy6JPFQvZlGfBdAMSakpciNe+UiW23qA/faJk92tF6rSU8npxDiPRglLVfPShSOuMSrYHR93N22kupDNbAAG8ycKECJSCAWfgy06w3FCaU4+1IAB0VKnldbp+wktXKnCN2XsloEgPFma923JHxDSv+tMCNvf+xd/d2n+xO5AT/mIx5VhLRORIOwYwjLzkQDRyOjUMKfJeda7LPbt4Gr4r0zHfh8x19JMozZTBI3Vu8BbcjkFSjywVnUgldHYd7LrU7I8UwwJwdZAf0nn3hldgM48FX80yBgjdAmVG0DvFqfp5jPDnJRaO9OtqIYhrflAjzXoI69x4BD2PkgIyqo8Y7/F+JS7LFmlGpwikMV4a4oCcZPOkMF29Apcd3fHC1af25yXKwxappXIcpvIegQ7WJMZyIOttQIuHP4oTTuWsBE6oEqjk0Q7B+k8pgBrQjwX2+X0kZ9C0ITaYa7ygLBizHYGL5ObVHr2E7NFPd/reXfKNs1N8fF9zEyVzhjLQVam2puZovy9bi/x9wR5yKbLi3lFxPZsMu3jbo6gqW0AsWnD429GNjwy549xKLWlypM9NO6Hwp6Mh877q3cEo17MeojHXbJhks=
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- geckodriver --version
- export MOZ_HEADLESS=1
env:
- MOZ_HEADLESS=1
jobs:
  include:
  - stage: test
    script: python manage.py test
  - stage: sonar-scanning
    script: sonar-scanner
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key:
        secure: YQpNnv8jwtUtl4lOkJO/4KrPRl5K4QkC6AFsvKAUoPI91oHiN3gdZr6DD1q8PtjcgLw6PGLsd6QyGVkBB135Wpy6CEQAD0UIYivqojY7f5fJTdV+ZEjaGOSSsWr7c6i2zivBIJAlprmoJdDhTz5qpMB9z+RK61whxHxRh2LTwD3ncKjZVJrlRgsBg8KT21iFZumjEKy2gBCZZikeCCUZlexPXr3xakYpTBeB7iukVfBjQ9D65Klr8OH7mrBv4fxuL5OYTM0RwXggSi7EJEjYKsHZXOvz26cCv3mllJwiEu+RJmDTDvrgLTfiMCvRmNJrAbVb0X3HOFscimCAVjNc+z65oXi45TQrs4lPYSQ9Wd0Qb62PYehxNk1Ih1l7o105ZMDoAkd5DFdrxeDkic88aI8G1+H1mbmNwlzAp4MaMICX53fMzDUY4AHnKn7fQVzFpXerxWNiDangBDjjL9h3PQ/KU/1r0bVFNyEzMORCH9H+S+uXNuZWhIHxV+A+NmuvfeQqMyhXCJwv2Kc11koCdrEPG7DIEfhBfXnaXv1LOgqBqIKa63hlGCv1k2cCEn40mLBBoiQyBse1BzdQiGo9xrp3asAF4hswSsGrJ5MfoQS2A2OSqluGL0GjdmBuBb56FEVDJS80Vx6nL/f39mM3ESGtBPphrlfEcXeSPY+/n1Q=
      skip_cleanup: true
      on:
        branch: staging
branches:
  only:
  - master
  - staging
#deploy:
#  api_key:
#    secure: YQpNnv8jwtUtl4lOkJO/4KrPRl5K4QkC6AFsvKAUoPI91oHiN3gdZr6DD1q8PtjcgLw6PGLsd6QyGVkBB135Wpy6CEQAD0UIYivqojY7f5fJTdV+ZEjaGOSSsWr7c6i2zivBIJAlprmoJdDhTz5qpMB9z+RK61whxHxRh2LTwD3ncKjZVJrlRgsBg8KT21iFZumjEKy2gBCZZikeCCUZlexPXr3xakYpTBeB7iukVfBjQ9D65Klr8OH7mrBv4fxuL5OYTM0RwXggSi7EJEjYKsHZXOvz26cCv3mllJwiEu+RJmDTDvrgLTfiMCvRmNJrAbVb0X3HOFscimCAVjNc+z65oXi45TQrs4lPYSQ9Wd0Qb62PYehxNk1Ih1l7o105ZMDoAkd5DFdrxeDkic88aI8G1+H1mbmNwlzAp4MaMICX53fMzDUY4AHnKn7fQVzFpXerxWNiDangBDjjL9h3PQ/KU/1r0bVFNyEzMORCH9H+S+uXNuZWhIHxV+A+NmuvfeQqMyhXCJwv2Kc11koCdrEPG7DIEfhBfXnaXv1LOgqBqIKa63hlGCv1k2cCEn40mLBBoiQyBse1BzdQiGo9xrp3asAF4hswSsGrJ5MfoQS2A2OSqluGL0GjdmBuBb56FEVDJS80Vx6nL/f39mM3ESGtBPphrlfEcXeSPY+/n1Q=
