language: python
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - printf '%s' $PATH